In [125]:
%cd /Users/yantong/Desktop/NLP\ for\ Risk/Code/

/Users/yantong/Desktop/NLP for Risk/Code


## Import Libraries


In [126]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [127]:
import matplotlib.pyplot as plt
from scipy.stats import gaussian_kde

In [128]:
import jieba as jb
import re

In [129]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import to_categorical
import numpy as np

from tensorflow.keras.layers import Dense, Input, Flatten, Dropout
from tensorflow.keras.layers import Conv1D, MaxPooling1D, Embedding
from tensorflow.keras.models import Sequential


In [130]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC
 
from sklearn.model_selection import cross_val_score


In [131]:
from sklearn.model_selection import GridSearchCV


In [132]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option("display.max_colwidth",None)
pd.set_option('display.width',None)

In [133]:
import json

## Read Data

In [134]:
split_data = pd.read_csv('baiduai_0_5224.csv')

In [135]:
split_data = split_data.loc[:4525] # split without stopwords

In [136]:
split_data = split_data.drop(['Unnamed: 0'],axis = 1)

## Data Preparation

In [118]:
seg_data = split_data[['content','split','baidu_seg','baidu_prob','label']]

In [119]:
seg_data_tran = seg_data.copy()

In [120]:
seg_data_tran['baidu_seg'] = seg_data_tran['baidu_seg'].apply(lambda row: eval(row))
seg_data_tran['baidu_prob'] = seg_data_tran['baidu_prob'].apply(lambda row: eval(row))

In [121]:
seg = []
prob = []
label = []
content = []
for row_idx in range(seg_data_tran.shape[0]):
    row_seg = seg_data_tran.loc[row_idx,'baidu_seg']
    row_prob = seg_data_tran.loc[row_idx,'baidu_prob']
    row_label = seg_data_tran.loc[row_idx,'label']
    row_content = seg_data_tran.loc[row_idx,'content']
    list_num = len(row_seg)
    for j in range(list_num):
        seg.append(row_seg[j])
        prob.append(row_prob[j])
        label.append(row_label)
        content.append(row_content)


In [109]:
newvalues = pd.DataFrame()
newvalues['content'] = content
newvalues['baidu_seg'] = seg
newvalues['baidu_prob'] = prob
newvalues['label'] = label

In [140]:
newvalues[newvalues.label == 1][newvalues.baidu_prob <0.4].head()

/opt/anaconda3/envs/tf2/lib/python3.7/site-packages/ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.


content  \
243                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 更多资讯可登录运营商财经网（telworld.com.cn），也可关注微信公众号tel_world近日，富力地产(02777)发布公告，公司股份已于2019年12月19日上午九时零四分起短暂停止买卖。消息一出，引起了业内的广泛讨论，还被曝出富力地产苏州两项目因违规擅自施工，合并被罚款超50万元。接二连三究竟是怎么了？据运营商财经网了解，苏州市住建局近日发布消息称，苏州富景房地产开发有限公司近期因“未取得建筑工程施工许可证即擅自施工”，两项目分别被罚款28.49万元、27.66万元。资料显示，苏州福景房地产实际控制方为富力地产。在苏地2018-WG-28号地块五（桩基工程及11#楼）工程项目建设中(面积：2848平方米，合同价：2660万元)，未办理质量监督手续、未办理安全监督手续、施工图设计文件未经审查、未取得建筑工程施工许可证的情况下，已由中国建筑一局（集团）有限公司，于2019年06月25日擅自施工。与此同时，在苏地2018-WG-28号地块四物业用房施工总承包工程项目建设中(面积：998.35平方米，合同价：2740万元)，未办理质量监督手续、未办理安全监督手续、施工图设计文件未经审查、未取得建筑工程施工许可证的情况下，已由中国建筑一局（集团）有限公司，于2019年06月25日擅自施工。运营商财经网还了解到，截至2019年11月，富力地产共实现合约销售金额约1203.5亿元，与年初制定的1600亿元目标还有396.5亿元的距离，这也意味今年上市公司终将完不成销售额。此次紧急停牌，有业内人士称或许与融资或转让项目有关，可以预见出作为中国地产企业十强的富力地产发展势头渐趋疲软，李思廉和张力下一步如何行动，值得观望。   
379  《科创板日报》（南京记者陈默）讯，一片冷清，可以用来形容如今的南京德科码项目现场，项目内部空无一人，东门口原有的两个门卫室也落了锁，里面铺了一层灰。从之前的红红火火，号称投资30亿美元，“建成后填补中国CIS产业空白”，到如今的一片冷清、欠薪被列为失信被执行企业，南京德科码经历了什么？12月2日，《科创板日报》记者前往南京德科码以5692万元所拍地块——南京市栖霞区液晶谷附近，该地块面积16.94万㎡，与德科码项目宣传用地254亩相吻合。该厂区几乎都被写有“中国建筑”的蓝色围挡围住，共有6个门，东边两个主门，正对三环路大道。据记者了解，能进入项目厂区的只有东边和北边的门，但这几个门均被上锁，无法进入，东边两个主门上标注褪色后的“中国建筑”4个字，上方钢结构的门头只有裸露的钢筋，两侧的宣传栏可以看出原来是项目规划图，目前已经破败不堪，只剩零星几片，让人无法辨别是何项目，好在门柱上的公示牌显示项目名称为南京德科码一期晶圆厂。从外往内看，正对东门有两个建筑物，一个为混凝土结构建筑，一个为上面1/3红色钢筋、下面2/3已浇筑混凝土的建筑。据记者了解，这两个建筑为生产楼和辅助楼，生产楼在去年2月上梁，但还没有封顶；辅助楼已经搭好了框架。项目北边也有两个门，分别是中电二公司承建的气站和远能电力承建的电站项目入口，但均大门紧闭，空无一人。西边的两个门是中国建筑第二工程局的项目部入口，进去后整齐地排列着一排排白色房屋，但该处与德科码生产楼等处中间，用蓝色隔板隔开。一位留守的工人表示：“我们现在工程队都撤了一年了，还剩几个人轮流看守。我们公司还曾在甲方办公楼那儿堵过，没用，要钱跟挤牙膏似的，但没钱怎么给他们干活呢？”一位从去年初就在附近工作的女士向《科创板日报》记者表示：“这个厂停工一年多了，去年就不干了，里面一个人都没有，我去年刚来的时候还有人，还跟门卫聊过天呢，门卫今年都回家了，门卫说是老板不给钱，工人不帮他干活了。”破败的项目现场，和德科码红火的开篇形成鲜明对比。2015年11月27日，德科码“CMOS图像传感器芯片（CIS）产业园”项目签约落户南京经济技术开发区（下称“南京开发区”），总投资约25亿美元；到了2016年6月8日项目举行奠基仪式时，宣布的总投资额已经达到30亿美元，金额和南京当年3月签约的台积电项目体量相当。在当地官方媒体的报道中，“建成后将填补中国CIS产业的空白”、“弥补南京电子信息产业‘缺芯’的不足”、“将填补国内相关产业的空白”等诸多溢美之词，都被加诸该项目上。一期项目为一座8吋晶圆厂，以电源管理芯片、微机电系统芯片生产为主，预计投产后产能可

In [139]:
# Check
newvalues[(newvalues.label == 1) & (newvalues.baidu_prob < 0.5)]

content  \
243                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  

In [66]:
#newvalues['label'] = newvalues['baidu_prob'].apply(lambda row: 1 if row>0.5 else 0)

In [67]:
#newvalues[newvalues.baidu_prob == 1]

In [68]:
newvalues.label.value_counts()

0    11853
1     2328
Name: label, dtype: int64

In [69]:
X = newvalues['baidu_seg']
y = newvalues['label']

## Modelling

### Model 1: TF-IDF + CNN

In [70]:
import kashgari
from kashgari import utils
from kashgari.embeddings import BertEmbedding
from kashgari.tasks.labeling import BiLSTM_CRF_Model
# from data_load import DataReader

/opt/anaconda3/envs/tf2/lib/python3.7/site-packages/tensorflow_addons/utils/ensure_tf_install.py:68: UserWarning: Tensorflow Addons supports using Python ops for all Tensorflow versions above or equal to 2.2.0 and strictly below 2.4.0 (nightly versions are not supported). 
 The versions of TensorFlow you are currently using is 2.4.0 and is not supported. 
Some things might work, some things might not.
If you were to encounter a bug, do not file an issue.
If you want to make sure you're using a tested and supported configuration, either change the TensorFlow version or the TensorFlow Addons's version. 
You can find the compatibility matrix in TensorFlow Addon's readme:
https://github.com/tensorflow/addons
  UserWarning,


In [71]:
from sklearn.model_selection import train_test_split


In [72]:
from tensorflow.keras.callbacks import TensorBoard
from kashgari.tasks.classification import CNN_Model

In [73]:
from sklearn.feature_extraction.text import TfidfVectorizer
 
tfidf = TfidfVectorizer(norm='l2', ngram_range=(1, 2))
#vectorizer = CountVectorizer()    
#features = tfidf.fit_transform(vectorizer.fit_transform(labeled_data_3.content_cut))
#labels = labeled_data_3.label
#print(features.shape)
#print('-----------------------------')
#print(features)
#print(labels)

In [74]:
X_train, X_test, y_train, y_test, indices_train, indices_test = train_test_split(X, y, 
                                                                                 newvalues.index, 
                                                                                 test_size=0.2, stratify=y, random_state=0)
X_test = X_test.tolist()
y_test = y_test.tolist()



X_train, X_val, y_train, y_val, indices_train, indices_val = train_test_split(X_train, y_train, 
                                                                                 indices_train, 
                                                                                 test_size=0.05, stratify=y_train, random_state=0)

X_train = X_train.tolist()
y_train = y_train.tolist()
X_val = X_val.tolist()
y_val = y_val.tolist()



In [75]:
# Using TensorBoard record training process
tf_board = TensorBoard(log_dir='tf_dir/cnn_model',
                       histogram_freq=5,
                       update_freq='batch')


In [76]:
model = CNN_Model()
model.fit(X_train, y_train, X_val, y_val,
          batch_size=128,
          callbacks=[tf_board])

Preparing text vocab dict: 100%|██████████| 568/568 [00:00<00:00, 21528.10it/s]
2020-12-28 16:43:27,605 [DEBUG] kashgari - --- Build vocab dict finished, Total: 38666 ---
2020-12-28 16:43:27,606 [DEBUG] kashgari - Top-10: ['[PAD]', '[UNK]', '[CLS]', '[SEP]', '项目', '企业', '发展', '建设', '公司', '工作']
Calculating sequence length: 100%|██████████| 568/568 [00:00<00:00, 782385.77it/s]
2020-12-28 16:43:27,727 [DEBUG] kashgari - Calculated sequence length = 180
2020-12-28 16:43:27,775 [DEBUG] kashgari - Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input (InputLayer)           [(None, None)]            0         
_________________________________________________________________
layer_embedding (Embedding)  (None, None, 100)         3866600   
_________________________________________________________________
conv1d (Conv1D)              (None, None, 128)         64128     
________________________

Epoch 1/5
84/84 [==============================] - 8s 91ms/step - loss: 0.4845 - accuracy: 0.8330 - val_loss: 0.3489 - val_accuracy: 0.8379
Epoch 2/5
84/84 [==============================] - 7s 89ms/step - loss: 0.2813 - accuracy: 0.8751 - val_loss: 0.2441 - val_accuracy: 0.9043
Epoch 3/5
84/84 [==============================] - 7s 88ms/step - loss: 0.1169 - accuracy: 0.9573 - val_loss: 0.2962 - val_accuracy: 0.8945
Epoch 4/5
84/84 [==============================] - 7s 82ms/step - loss: 0.0353 - accuracy: 0.9910 - val_loss: 0.3996 - val_accuracy: 0.8848
Epoch 5/5
84/84 [==============================] - 7s 78ms/step - loss: 0.0092 - accuracy: 0.9981 - val_loss: 0.4912 - val_accuracy: 0.8828


In [318]:
import os
import joblib
os.chdir("saved_model_split")
model.save('tfidf_cnn')

FileNotFoundError: [Errno 2] No such file or directory: 'saved_model_split'

In [319]:
os.chdir("..")

In [320]:
model.evaluate(X_test, y_test)

2020-12-28 16:32:23,778 [WARNING] kashgari - Sequence length is None, will use the max length of the samples, which is 209
2020-12-28 16:32:23,952 [DEBUG] kashgari - predict input shape (2837, 209) x: 
[[    2    30 19751 ...     0     0     0]
 [    2  9939  1123 ...     0     0     0]
 [    2   236  8487 ...     0     0     0]
 ...
 [    2  2893  3923 ...     0     0     0]
 [    2 21282 21856 ...     0     0     0]
 [    2 24117  1797 ...     0     0     0]]
2020-12-28 16:32:24,483 [DEBUG] kashgari - predict output shape (2837, 2)
2020-12-28 16:32:24,487 [DEBUG] kashgari - predict output argmax: [0 0 1 ... 0 0 0]


              precision    recall  f1-score   support

           0     0.9123    0.9566    0.9339      2371
           1     0.7066    0.5322    0.6071       466

    accuracy                         0.8869      2837
   macro avg     0.8094    0.7444    0.7705      2837
weighted avg     0.8785    0.8869    0.8802      2837



{'detail': {'0': {'precision': 0.912308930008045,
   'recall': 0.9565584141712358,
   'f1-score': 0.9339098208770845,
   'support': 2371},
  '1': {'precision': 0.7065527065527065,
   'recall': 0.5321888412017167,
   'f1-score': 0.6070991432068543,
   'support': 466},
  'accuracy': 0.8868523087768769,
  'macro avg': {'precision': 0.8094308182803758,
   'recall': 0.7443736276864763,
   'f1-score': 0.7705044820419694,
   'support': 2837},
  'weighted avg': {'precision': 0.8785118203393147,
   'recall': 0.8868523087768769,
   'f1-score': 0.880228546363751,
   'support': 2837}},
 'precision': 0.8785118203393147,
 'recall': 0.8868523087768769,
 'f1-score': 0.880228546363751,
 'support': 2837}

In [322]:
newvalues[newvalues.baidu_prob>0.5].sample(n = 100)

baidu_seg  \
7493                                                                                                                                                                       [标书, 制作, 软件, 操作, 问题, 咨询, 400, 819, 8786, 6, 业绩, 年限, 投标人, 须知, 前, 附表, 3.1.2, 里面, 4, 业绩, 表, 4.1, 4.2, 业绩, 年限, 应当, 招标, 文件, 详细, 评审, 标准, 业绩, 年限, 一致, 两者, 不, 一致, 联系, 招标, 公告, 投标, 咨询, 联系人, 确认, 四, 标书, 递交, 1, 开标, 前, 最好, 提前, 2天, 上传, 加密, 技术, 商务, 电子, 标书, 避免, 上传, 出现, 问题, 无法, 解决, 2, U盘, 形式, 递交, 未, 加密, 版, 技术, 标, 商务标, 电子版, (, 须, 上传, 加密, 版, 生成, 版本, 无法, 上传, ), 必须, 纸质, 版, 投标, 文件, 一并, 递交, 投标, 截止, 时间, 递交, 投标, 文件, 不予, ...]   
4422                                                        [工商, 资料, 显示, 华盛汇丰公司, 股东, 华盛燃气有限公司, 以下, 简称, 华盛, 燃气, 上海曼佩企业管理咨询有限公司, 以下, 简称, 上海曼佩公司, 占, 股, 51%, 49%, 华盛, 燃气, 天壕环境股份全资子公司, 2016年11月24日, 中联煤层气有限责任公司, 以下, 简称, 中联, 煤层气, 国家能源局, 申报, 神安线, 项目, 列入, 国家能源局, 煤层气, 煤矿, 瓦斯, 开发, 利用, 十三五, 规划, 中联, 煤层气, 身份, 更为, 惹眼, 中海油全资子公司, 成立, 1996年5月13日, 经营, 范围, 包括, 煤层气, 开采, 胡坦, 等人, 质疑, 华盛汇丰公司, 在此, 半年, 多, 前, 中海油, 名义, 对外, 项目, 招标, 华盛汇丰公司, 首次, 中海油, 一起, 出现, 神安线, 项目, 合作, 2017年, 4月17至18日, 文件, 显示, 中海油咨询中心, 受, 中海油, 规划部, 委托, 北京, 组织, 召开, 神安线, 项目, 工程, 预, 可行性, 研究, 报告, 专家, 评审会, 华盛, 汇丰公司, 项目, 潜在, 合作, ...]   
6225                                                                                                                                                                                                                                                                                                                                                                                 [当前, 国, 石油, 化学工业, 产品, 仍然, 不能, 完全, 满足, 消费, 升级, 需要, 高端, 供给, 不足, 大量, 依赖, 进口, 中国石化, 联合会, 设立, 科学技术, 奖, 加快, 实施, 创新, 驱动, 发展, 战略, 充分, 调动, 广大, 科技, 人员, 积极性, 创造性, 促进, 石油, 化工, 行业, 科技, 进步, 奖项, 每年, 评审, 授奖, 一次, 杨明]   
513                                                           [格隆汇, 12月18日, 丨, 启迪, 环境, (, 000826, 股吧, ), (, 000826.SZ, ), 公布, 2018年2月, 公司, 收到, 广西省, 南宁市, 武鸣区, 住房, 城乡规划建设局, (, 武鸣区住建局, ), 发, 中标通知书, 确定, 公司, 牵头, 单位, 联合体, (, 联合体, 成员, 单位, 中国市政工程华北设计研究总院有限公司, 中国建筑第五工程局有限公司, 江苏聚慧科技有限公司, ), 成为, 南宁市, 武鸣区, 流域, 水, 环境, 综合, 整治, PPP, 项目, 中标, 单位, 2018年2月, 武鸣区住建局, 南宁广西富鸣城市投资发展集团有限责任公司, 公司, 牵头, 单位, 联合体, 广西壮族自治区, 南宁市, 签署, 南宁市, 武鸣区, 流域, 水, 环境, 综合, 整治, PPP, 项目, 合同, 联合体, 成员, 未能, 业主方, 项目, 公司, 资金, 投入, 主要, 项目, 实施, 条件, 达成, 一致, 意见, 目前, 项目, 实施, 尚存, 实质性, 障碍, 业主, 方, 拟, 联合体, 成员, 解除, 南宁市, 武鸣区, ...]   
10091                                                                                                                                     [目前, 披露, 增资, 股份, 推算, 中央, 汇金, 成为, 恒丰银行, 第一, 大, 股东, 山东, 金融, 资产, 成为, 该行, 第二, 大, 股东, 新加坡大华银行, 第三大, 股东, 战略, 投资者, 引入, 会, 恒丰银行, 带来, 影响, 恒丰银行, 人士, 山东省财政厅, 省政府, 履行, 出资, 人, 职责, 代表, 山东, 金融, 资产, 入股, 恒丰银行, 发行, 股份, 方案, 尚, 需, 监管, 机构, 批准, 该行, 已经, 启动, 报批, 程序, 市场化, 改革, 完成, 恒丰银行, 资本, 实力, 显著, 增强, 流动性, 稳健, 充裕, 资产质量, 向好, 监管, 指标, 达到, 优良, 身为, 12家, 全国性, 股份制, 银行, 一, 恒丰银行, 近几年, 发展, 历程, 总是, 出现, 风波, 尤其, 该行, 两位, 董事长, 接连, 被查, 引发, 市场, 关注, 2014年, 该行, 原, 董事长, ...]   
10906                                                                                                                                                [整个, 资本市场, 证券日报, 记者, 中国国家铁路集团有限公司, 1月2日, 召开, 工作会议, 了解到, 2019年, 政府工作报告, 部署, 铁路, 投资, 任务, 全面, 完成, 全国, 铁路, 固定资产, 投资, 完成, 8029亿元, 国家, 铁路, 完成, 7511亿元, 投产, 铁路, 新, 线, 8489公里, 包括, 高铁, 5474公里, 2019年, 年底, 全国, 铁路, 营业, 里程, 达到, 13.9万公里, 包括, 高铁, 3.5万公里, 郑重, 声明, 东方财富网, 发布, 信息, 目的, 传播, 更多, 信息, 站立, 场, 无关, 东方财富网, 不, 保证, 信息, 包含, 不, 限于, 文字, 视频, 音频, 数据, 图表, 部分, 内容, 准确性, 真实性, 完整性, 有效性, 及时性, 原创性, 相关, 信息, 并未, 本网站, 证实, 不对, 构成, 投资, 建议, 操作, 风险, 担]   
854                                                                                                                                                    [满目疮痍, 荒山, 泥泞, 坑洼, 山路, 简陋, 偏僻, 板房, …, …, 此前, 10余年, 工程, 建设, 经验, 李海龙, 淬炼, 成, 行业, 精英, 管廊, 建设, 李海龙, 一条, 小白龙, 一条, 小白龙, 进入, 浅水滩, 地下, 均, 大面积, 坚硬, 岩石, 一路, 伴随, 爆破, 前行, 李海龙, 介绍, 介绍, 喀斯特地形, 环境, 建设, 城市, 综合管廊, 难度, 超出, 预料, 遇到, 地下溶洞, 软, 土层, 情况, 会, 更加, 困难, 工作量, 会, 常规, 工艺, 5倍, 了解, 施工, 过程, 建设者, 刚, 一段, 基槽, 开挖, 地下, 6.2米, 发现, 200米, 范围, 内, 都是, 松软, 地质, 层, 相邻, 地段, 岩石区, 容易, 造成, 沉降, 不, 均匀, 管廊, 建成后, 就会, 